data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/00275/Bike-Sharing-Dataset.zip
data_file_name: hour.csv

artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv

  split_local_dir: split_local_dir
  train: train.csv
  test: test.csv

  model_dir: model_dir
  model_filename: pipeline.model

  reports_dir: reports_dir
  scores: scores.json